
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 65)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ASTERISCO = 5;
  public static final int PUNTO = 8;
  public static final int ALTER = 9;
  public static final int PAR_IZQ = 3;
  public static final int EOF = 0;
  public static final int PAR_DER = 4;
  public static final int MAS = 6;
  public static final int ID = 2;
  public static final int error = 1;
  public static final int INTERROGACION = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "PAR_IZQ",
  "PAR_DER",
  "ASTERISCO",
  "MAS",
  "INTERROGACION",
  "PUNTO",
  "ALTER"
  };
}

